### ISSUE TITLE
OTA network ports show in all 1.8.X versions but not in any 2.X versions of IDE

### ISSUE THREAD

**Issue by HomeSpan** [arduino/mdns-discovery#25]
### Describe the problem

I am using the ArduinoOTA library that is included with Arduino-ESP32 (version 2.0.2) and under Arduino 1.8.19 every works fine.  I can see all of my ESP2 devices under the Port menu in 1.8.19.   I can also see the MDNS broadcasts are working.  However, none of the devices show up under Arduino IDE 2.0.0 RC 6 (or any previous versions).  Based on other posted issues it appears that there was some problem with showing device names, but nothing about the lack of any devices showing up at all.  Are there other MDNS items that must be broadcast that are required by 2.0.0 that were not required by 1.8.19?  Or perhaps a preference setting in IDE 2.0.0 that enables network ports to be shows?

### To reproduce

Compile and load ArduinoOTA->BasicOTA Example from Arduino-ESP32.  After running, board shows up as network port under IDE 1.8.19, but does show up an network port under 2.0.0 RC6.

### Expected behavior

Expected board to show up under network port within 2.0.0 RC 6.

### Arduino IDE version

2/0/0

### Operating system

macOS

### Operating system version

12.3.1

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Thanks for the information and for sharing the workaround @HomeSpan!

Since we have determined that it is not directly caused by Arduino IDE 2.x, I have transferred the issue to the mdns-discovery repository's issue tracker.

**Comment by sebromero** [comment]
@per1234 Let me know if you need me to test something.

**Comment by datort** [comment]
Is there anything more I could provide to help get this sorted?

**Comment by per1234** [comment]
Thanks all. I am mostly in the triage role here and don't know much about the subject. It will likely be very helpful for the developers to have the assistance of those who are able to reproduce the issue once the time comes for a more in depth investigation and fix.

If you are interested in going further with this, you can try to [bisect](https://en.wikipedia.org/wiki/Bisection_(software_engineering)) the problem. **@[]()HomeSpan** found that the problem occurs with the 1.0.5 release, but not with the 0.9.2 release. That is useful, but it still leaves a large range of changes that might have introduced the problem:

https://github.com/arduino/mdns-discovery/compare/0.9.2...v1.0.5

The low hanging fruit would be to download the binaries for each of the releases from that range and bisect to the release. You would simply repeat the procedure I described in my previous reply, except using the `mdns-discovery` binary downloaded from the release instead of from the `~/Library/Arduino15/packages/builtin/tools/mdns-discovery` folder.

The binaries are available for download from the "**Assets**" section of each of the release pages:

https://github.com/arduino/mdns-discovery/releases

After that, if you want to get a bit more fancy by bisecting to the specific commit. That will require checking the repository out to each commit in the range between the last "good" release and the first "bad" release, then  building the project from the source code using Go.

The bisection might also be helpful for those who want to use the workaround described by **@[]()HomeSpan** because you could use the most recent available "good" version as the replacement for the "bad" 1.0.5.

**Comment by HomeSpan** [comment]
The issue begins with release 1.0.0, which seems to be a complete refactoring of 0.9.2.  I noticed in the source code the v1.0.0 tries to consume an IP6 address.  My boards are no broadcasting an IP6 address (only IP4), and the error message @datort noted above is related to IP6.  Perhaps that is the source of the problem?

**Comment by Maarkk** [comment]
[per1234](https://github.com/per1234) - What do you mean by "plug/unplug" Arduino board? My boards are just network devices, visible as network ports in Arduino IDE 1.x but not in most recent Arduino IDE 2 (i cannot physically plug them into main computer ;))
mdns-discovery worked ok till 10 - it showed "ok", but no other results...

**Comment by per1234** [comment]
Hi @Maarkk I apologize for the confusion. The instructions were based on the ones I previously wrote for serial discovery troubleshooting. In this case, instead of:

> 9. Unplug your Arduino board from your computer if you have it plugged in.

I should have written this:

> 9. Disconnect your Arduino board from its power source if you have it powered.

Instead of:

> 12. Plug your Arduino board into your computer

I should have written:

> 12. Power your Arduino board

Instead of:

> 13. Unplug your Arduino board from your computer

I should have written:

> 13. Disconnect your Arduino board from its power source

**Comment by Maarkk** [comment]
Thanks - that clears the thing :)
Anyway, symptoms are different in my case - no results from mdns-discovery (checked with Bonjour tool for Windows - it shows Arduino nodes/services).

**Comment by per1234** [comment]
>no results from mdns-discovery

I have the same problem on my Windows machine. It works perfectly on my Linux machine though.

**Comment by datort** [comment]
A few things i've learned the other day concerning the initial issue I'd like to share: 

For me it turns out, that it's really just IPV6 related. The issue is the same on my Mac and Windows machine with mdns-discovery v1.0.5. After an update, my router supports (favors?) IPV6 addresses even in my local network. While Macs/PCs and the ESP board have their IPV4 addresses, Mac/PC also get's an IPV6. 

If I switch off the IPV6 support in my router and let the Mac/PC update their DHCP-given addresses, Arduino IDE 2.x is able to find the boards. If have some more issues with Arudino IDE after that, but's probably another issue or some research on my side.

**Comment by mcspr** [comment]
Any updates? I have also noticed a weird issue running on Windows; mDNS packets only go to localhost interface, and nothing goes to the actual real network when running `arduino-cli board list`.

Maybe OT: looking at internals of arduino-cli and mdns-discovery... hashicorp/mdns example from README *does work* when I write a little program and select some specific interface via `net.InterfaceByName()` / `net.InterfaceByIndex()`. However, it does not work without specifying one, like it happens here.

**Comment by whitevast** [comment]
IDE version 1 always sees ESP-LINK boards, IDE version 2 can SOMETIMES see them. But not for long... If I change mdns-discovery.exe on version 0.9.2, the detection is always successful.

**Comment by cmaglie** [comment]
Closing as solved with the release 0.9.2 that has been published weeks ago now.

**Comment by davygravy** [comment]
This seems to still be a problem.   On Debian 12.9, 0.9.2 works perfectly, but neither 1.0.9 nor 1.0.10 work (with any usable reliability).

I've tested with the CLI steps above and I get no (or only sporadic/unreliable) discovery output  from 10.0.9/10 after the START_SYNC.

Not sure where the change occured after 0.9.2, but it is not working in 1.0.9/10.

============

I worked around this by creating a dir  `~/.arduino15/packages/builtin/tools/mdns-discovery/1.5.10/` and copying the contents of `0.9.2` into it.


Please reopen.

**Comment by seb1k** [comment]
The problem still occur today.
Config :
Windows 10
Arduino 2.3.10

Replacing` .../mdns-discovery/1.0.9/mdns-discovery.exe` to`.../mdns-discovery/1.0.12/mdns-discovery.exe` solved the issue.
